### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [prioritizr/prioritizrdata#10]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by jeffreyhanson** [comment]
Thank you very much for the heads up @rsbivand!

**Comment by rsbivand** [comment]
[00check.log](https://github.com/prioritizr/prioritizrdata/files/11141226/00check.log)
is a recent check log from running under `_SP_EVOLUTION_STATUS_=2` without retiring r-spatial packages (suggested in this package) on the library path. I think that the next release should clear this.

**Comment by rsbivand** [comment]
Good luck! I can run check w/o the retiring packages on your submission tarball if you like, if you attach it here.

**Comment by jeffreyhanson** [comment]
Thanks for the offer! Since the new version will replace sp/rgeos/rgdal with sf, I don't think would be needed?

**Comment by rsbivand** [comment]
Maybe. Sometimes other packages your package uses draw something in "by accident", so only removing the retiring packages from the library path actually checks this.

**Comment by jeffreyhanson** [comment]
Oh I see - thank you very much for explaining why the check is still useful and for running the check too!
