### ISSUE TITLE
Saltspring vignette + documentation

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizrdata#2]
I made a few changes to the Salt Spring data set documentation and vignette to try and improve them. Could @ricschuster or @ninamorrell take a look at it and confirm that I haven't used the wrong citations or terminology? 

For instance, the name "Saltspring" was officially listed as "Salt Spring" on Wikipedia, so I renamed it "Salt Spring". Is this correct? Should it be named "Saltspring" or "Salt Spring"?

**Comment by ricschuster** [comment]
I did a quick check and it looks okay. I think officially its called Salt Spring, so good to have this align with the official spelling, thanks.

**Comment by jeffreyhanson** [comment]
Ok, thanks for looking over it. I'll close this now.
