### ISSUE TITLE
Tasmania case-study data has a CRS that causes annoying issues

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizrdata#5]
It would appear that the recent-ish PROJ7 update means that we can no longer switch between `sf::crs` and `sp::CRS` objects easily, and some coordinate systems do not round trip correctly when reading and writing from disk. Normally, this would be a user-level problem that we wouldn't deal with (i.e. it would be up to the user to specify/find a valid CRS), but I feel like we should avoid these issues with the built-in datasets. For example,

```
# load packages and data
library(prioritizr)
library(prioritizrdata)

# load data and set crs
data(tas_features)
tas_features@crs <- as(st_crs(3577), "CRS")

# round trip from disk
writeRaster(tas_features, "test.tif")
tas_features2 <- stack("test.tif")

# compare crs
st_crs(tas_features) == st_crs(tas_features2)
``` 

To avoid this, I propose updating the Tasmania example case-study data to use a different equal-area coordinate system that does not have such issues. Specifically, UTM Zone 55 South. @ricschuster, how does that sound? I can sort this out and  upload the new dataset?

**Comment by ricschuster** [comment]
Agreed, would be good to avoid this.
Thanks very much for taking this on  @jeffreyhanson!

**Comment by jeffreyhanson** [comment]
Ok great - I'll push a new version to GitHub today that will be a release candidate for CRAN.

**Comment by jeffreyhanson** [comment]
I just checked the Salt Spring Island data, and it too suffers from this same problem.

```
## load packages and data
library(prioritizr)
library(prioritizrdata)

setwd("C:\\Users\\jhanson\\Downloads\\data")

## load data and set crs
data(salt_features)

## this is needed to update the CRS-class to be compatible with 
## new version of sp package
crs(salt_features) <- sp::CRS(salt_features@crs@projargs)
# Warning message:
# In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
#   Discarded datum WGS_1984 in CRS definition,
# but +towgs84= values preserved

## round trip from disk
writeRaster(salt_features, "test.tif")
# Warning message:
# In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
#   Discarded datum WGS_1984 in CRS definition,
# but +towgs84= values preserved

salt_features2 <- stack("test.tif")
# Warning message:
# In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
#   Discarded datum WGS_1984 in CRS definition,
# but +towgs84= values preserved

## compare crs
st_crs(salt_features) == st_crs(salt_features2)
# FALSE
```

What do you think about updating the CRS for this dataset too? Would UTM Zone 10 be the correct zone for this dataset?

**Comment by ricschuster** [comment]
Updating the CRS for this dataset as well sounds good.
Yes, UTM Zone 10 is the correct one for that zone. 
Thanks!

**Comment by ricschuster** [comment]
Should we bump to version 0.2.3 and release to CRAN?

**Comment by jeffreyhanson** [comment]
Yes but not yet. The current version of prioritizr on CRAN has tests that will fail with this new version of prioritizrdata (basically, the tests need an `na.rm = TRUE` for this new reprojected data). So this means that we need to update the version of prioritizr on CRAN before we can update the version of prioritizrdata on CRAN. However, before we can update prioritizr on CRAN, we need to wait for an updated version of fasterize on CRAN (the super awesome @jeroen has a PR to fix fasterize so it won't be archived). This is because you received an email from Ripley asking that we remove fasterize as a dependency from prioritizr because fasterize was failing some CRAN checks and scheduled for archival. So, the update order is (1) wait for fasterize to be updated on CRAN, (2) release prioritizr update on CRAN, and (3) release prioritizr on CRAN. Does that sound right? Am I missing something? If that sounds good to you, I'll do a version bump for both prioritizr and prioritizrdata once fasterize has been updated on CRAN?

**Comment by ricschuster** [comment]
Awesome! 

Just working on checking prioritizr/prioritizr#153 now.

**Comment by jeffreyhanson** [comment]
Excellent - thanks!

**Comment by jeffreyhanson** [comment]
@ricschuster, just a heads up, the new version of fasterize is now on CRAN so we can begin preparing for CRAN releases of prioritizrdata and prioritizr. 

Also, I got an email from CRAN about a package that I maintain (https://www.stats.ox.ac.uk/pub/bdr/donttest/raptr.out) and it looks like they will be testing example code in wrapped in `\donttest` (which is pretty counter intuitive) . So I'll need to replace any `\donttest` with `\dontrun` in the examples as well as the version bump + rebuilding package websites.

**Comment by ricschuster** [comment]
Thanks for the heads up @jeffreyhanson 
Well that just makes no sense at all. 
What's going on with CRAN lately?

**Comment by jeffreyhanson** [comment]
I just pushed an update to bump the version and rebuild the site, so I'll close this issue now.

**Comment by jeffreyhanson** [comment]
Oh, sorry, I forgot to respond to your question: Yeah, I don't know. It seems like they are starting to enforce some weird policies.
